[build]
  command = "npm run build"
  publish = "out"
  
[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "8"
  NEXT_TELEMETRY_DISABLED = "1"
  
# Production context
[context.production]
  command = "npm run build"
  
# Deploy preview context  
[context.deploy-preview]
  command = "npm run build"
  
# Branch deploy context
[context.branch-deploy]
  command = "npm run build"

# Redirects for client-side routing and SEO
[[redirects]]
  from = "/home"
  to = "/"
  status = 301

[[redirects]]
  from = "/contact-us"
  to = "/#contact"
  status = 301
  
[[redirects]]
  from = "/about-us" 
  to = "/#platform"
  status = 301
  
[[redirects]]
  from = "/solutions"
  to = "/#ecosystem"
  status = 301
  
[[redirects]]
  from = "/demo"
  to = "/#contact"
  status = 301

# Handle client-side routing (SPA fallback)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"

# Performance headers for static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/favicon.ico"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Plugin configuration
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Development settings
[dev]
  command = "npm run dev"
  port = 3000
  publish = "out"
  autoLaunch = false
